import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B1D3A',
    padding: 16,
    justifyContent: 'center',
    gap: 10,
  },
  titulo: {
    fontSize: 22,
    fontWeight: '700',
    color: '#ffff',
    alignSelf: 'center',
    paddingTop: 50,
  },
  subtitulo: {
    fontSize: 14,
    lineHeight: 20,
    color: '#a7a6a6',
    marginBottom: 8,
    textAlign: 'center',
  },
  botaoSecundario: {
    borderWidth: 1,
    borderColor: '#00ABE4',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 20,
  },
  botaoSecundarioTexto: {
    color: '#00ABE4',
    fontWeight: '700',
  },
  cardContainer: {
    flexDirection: 'row',
    backgroundColor: '#123368',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    elevation: 3,
    marginVertical: 12,
  },
  containerImagem: {
    flex: 4.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  caixaDaguaImg: {
    width: '100%',
    aspectRatio: 1, 
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
  },
  containerInformacoes: {
    flex: 5.5, 
    flexDirection: 'column',
    gap: 12,
  },
  blocoInfo: {
    flex: 1,
    minHeight: 100,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: '3%',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    marginHorizontal: '1%',
  },
  blocoLitros: {
    backgroundColor: '#fef2f2', 
    borderLeftWidth: 4,
    borderLeftColor: '#ef4444',
  },
  blocoVolume: {
    backgroundColor: '#f0fdf4',
    borderLeftWidth: 4,
    borderLeftColor: '#22c55e',
  },
  rotuloInfo: {
    fontSize: 10,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    fontWeight: '700',
    marginBottom: 8,
    textAlign: 'center',
  },
  valorInfo: {
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    flexWrap: 'wrap',
    textShadowOffset: {
      width: 0,
      height: 0,
    },
    textShadowRadius: 8,
  },
  containerIstatisticas: {
    flexDirection: 'row',
    width: '100%',
    maxWidth: 1200,
    backgroundColor: 'rgba(12, 31, 58, 0.75)',
    borderRadius: 24,
    paddingVertical: 18,
    paddingHorizontal: '4%',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(120, 180, 255, 0.25)',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 12,
    overflow: 'hidden',
    alignSelf: 'center',
  },
    containerGraficos:{

    },
});